"use client";

import { useRouter } from "next/navigation";
import { MarketingLayout } from "@/components/marketing-layout";

export default function IntelligenceAnalystsPage() {
  const router = useRouter();

  return (
    <MarketingLayout>
      <div className="pt-24 pb-16 px-6">
        <div className="max-w-5xl mx-auto">
          <button
            onClick={() => router.push("/")}
            className="text-sm text-[#00D4FF] hover:underline mb-8 inline-block cursor-pointer"
          >
            &larr; Back To Home
          </button>

          {/* Hero */}
          <div className="text-center mb-16">
            <h1 className="text-3xl sm:text-5xl font-bold font-[family-name:var(--font-chakra-petch)] mb-4">
              For{" "}
              <span className="text-[#00D4FF]">Intelligence Analysts</span>
            </h1>
            <p className="text-gray-400 text-lg max-w-3xl mx-auto leading-relaxed">
              You spend hours scraping FCC IBFS, cross-referencing EDGAR filings,
              and manually tracking orbital data. SIG/NAIC does it in
              seconds and alerts you when something changes.
            </p>
          </div>

          {/* Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
            <div className="rounded-xl border border-[#1a1a2e] bg-[#0A0A1A] p-6">
              <h3 className="text-lg font-semibold text-white mb-3 font-[family-name:var(--font-chakra-petch)]">
                Signal Overload
              </h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                Thousands of FCC filings, contract awards, and patent
                applications are published every month across dozens of
                government databases. You are missing critical competitive
                signals because no human can monitor everything manually.
                SIG/NAIC monitors all sources continuously and surfaces
                the signals that matter to your mission.
              </p>
            </div>

            <div className="rounded-xl border border-[#1a1a2e] bg-[#0A0A1A] p-6">
              <h3 className="text-lg font-semibold text-white mb-3 font-[family-name:var(--font-chakra-petch)]">
                Siloed Data
              </h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                FCC data lives on one government site, contracts on another,
                patents on a third, orbital data requires a separate login
                entirely. Connecting a company&apos;s filing activity to their
                contract wins to their patent strategy requires hours of manual
                cross-referencing across disconnected systems.
                SIG/NAIC connects everything in one queryable platform.
              </p>
            </div>

            <div className="rounded-xl border border-[#1a1a2e] bg-[#0A0A1A] p-6">
              <h3 className="text-lg font-semibold text-white mb-3 font-[family-name:var(--font-chakra-petch)]">
                Reporting Lag
              </h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                By the time your weekly intelligence brief is assembled manually
                from multiple sources, the intelligence is already days old. Your
                competitors may already be acting on it.
                SIG/NAIC&apos;s Orbital Brief is generated by AI with the
                latest data and delivered to your inbox on your schedule.
              </p>
            </div>

            <div className="rounded-xl border border-[#1a1a2e] bg-[#0A0A1A] p-6">
              <h3 className="text-lg font-semibold text-white mb-3 font-[family-name:var(--font-chakra-petch)]">
                How SIG/NAIC Solves It
              </h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                Automated monitoring across all government and industry data
                sources. Ask Raptor for instant cross-source analysis on any
                question. Orbital Briefs delivered before your morning coffee.
                Spend your time analyzing intelligence and making
                recommendations, not collecting and formatting data.
              </p>
            </div>
          </div>
        </div>
      </div>
    </MarketingLayout>
  );
}
