import type jsPDFType from "jspdf";

interface ExportTableOptions {
  title: string;
  subtitle?: string;
  columns: string[];
  rows: (string | number)[][];
  filters?: string;
  filename: string;
}

function addHeader(doc: jsPDFType, title: string, filters?: string) {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Brand header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 17, 17);
  doc.text("SIG/NAIC", 14, 18);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(102, 102, 102);
  doc.text("SPACE INTELLIGENCE", 50, 18);

  // Cyan accent line
  doc.setDrawColor(6, 182, 212);
  doc.setLineWidth(1.5);
  doc.line(14, 22, pageWidth - 14, 22);

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 17, 17);
  doc.text(title, 14, 32);

  // Date
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(102, 102, 102);
  doc.text(
    `Generated: ${new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })}`,
    14,
    38
  );

  let startY = 42;

  // Filters
  if (filters) {
    doc.setFontSize(8);
    doc.setTextColor(102, 102, 102);
    doc.text(`Filtered by: ${filters}`, 14, startY);
    startY += 6;
  }

  return startY;
}

function addFooter(doc: jsPDFType) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(153, 153, 153);
    doc.text("Generated by Signaic — signaic.com", 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 40, pageHeight - 10);
  }
}

export async function exportTableToPDF({
  title,
  subtitle,
  columns,
  rows,
  filters,
  filename,
}: ExportTableOptions) {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");
  const doc = new jsPDF({ orientation: rows[0]?.length > 5 ? "landscape" : "portrait" });

  let startY = addHeader(doc, title, filters);

  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(102, 102, 102);
    doc.text(subtitle, 14, startY);
    startY += 6;
  }

  autoTable(doc, {
    startY,
    head: [columns],
    body: rows,
    styles: {
      fontSize: 7,
      cellPadding: 3,
      textColor: [51, 51, 51],
      lineColor: [226, 228, 232],
      lineWidth: 0.5,
    },
    headStyles: {
      fillColor: [10, 22, 40],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 7,
    },
    alternateRowStyles: {
      fillColor: [248, 249, 251],
    },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc);
  doc.save(filename);
}

export async function exportChartToPDF(
  elementId: string,
  title: string,
  filename: string
) {
  const { default: jsPDF } = await import("jspdf");
  const { default: html2canvas } = await import("html2canvas");
  const element = document.getElementById(elementId);
  if (!element) return;

  const canvas = await html2canvas(element, {
    backgroundColor: "#ffffff",
    scale: 2,
  });

  const imgData = canvas.toDataURL("image/png");
  const imgWidth = canvas.width;
  const imgHeight = canvas.height;

  const doc = new jsPDF({
    orientation: imgWidth > imgHeight ? "landscape" : "portrait",
  });

  const startY = addHeader(doc, title);
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - 28;
  const scaledHeight = (imgHeight * maxWidth) / imgWidth;

  doc.addImage(imgData, "PNG", 14, startY, maxWidth, scaledHeight);

  addFooter(doc);
  doc.save(filename);
}

export async function exportDashboardToPDF(
  elementId: string,
  title: string,
  filename: string
) {
  const { default: jsPDF } = await import("jspdf");
  const { default: html2canvas } = await import("html2canvas");
  const element = document.getElementById(elementId);
  if (!element) return;

  const canvas = await html2canvas(element, {
    backgroundColor: "#f8f9fb",
    scale: 1.5,
    logging: false,
    useCORS: true,
  });

  const imgData = canvas.toDataURL("image/png");
  const doc = new jsPDF({ orientation: "landscape" });

  const startY = addHeader(doc, title);
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - 28;
  const scaledHeight = (canvas.height * maxWidth) / canvas.width;

  doc.addImage(imgData, "PNG", 14, startY, maxWidth, scaledHeight);

  addFooter(doc);
  doc.save(filename);
}
