/* eslint-disable @typescript-eslint/no-require-imports */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const dotenv = require("dotenv");
dotenv.config({ path: ".env.local" });

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createClient } = require("@supabase/supabase-js");

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  }
);

interface SeedEntity {
  name: string;
  slug: string;
  type: "company" | "agency" | "program";
  sectors: string[];
  description: string;
  website: string;
  ticker_symbol: string | null;
  headquarters: string;
  key_programs: string[];
  founded_year: number;
  employee_count_estimate: number;
  annual_revenue_estimate: string | null;
  last_activity: null;
  source_counts: Record<string, never>;
}

// ─── LAUNCH PROVIDERS (10) ──────────────────────────────────────────────────
const launchProviders: SeedEntity[] = [
  {
    name: "Rocket Lab",
    slug: "rocket-lab",
    type: "company",
    sectors: ["launch", "satellites", "space systems"],
    description:
      "End-to-end space company providing launch services with Electron and developing the medium-lift Neutron rocket. Also manufactures spacecraft components and satellite buses through its Space Systems division.",
    website: "https://www.rocketlabusa.com",
    ticker_symbol: "RKLB",
    headquarters: "Long Beach, California, USA",
    key_programs: ["Electron", "Neutron", "Photon", "HASTE", "Pioneer reaction wheels"],
    founded_year: 2006,
    employee_count_estimate: 2000,
    annual_revenue_estimate: "$245M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Relativity Space",
    slug: "relativity-space",
    type: "company",
    sectors: ["launch", "advanced manufacturing"],
    description:
      "Aerospace manufacturer using proprietary 3D printing technology to build rockets. Developing the fully reusable Terran R medium-lift vehicle after retiring the Terran 1 pathfinder.",
    website: "https://www.relativityspace.com",
    ticker_symbol: null,
    headquarters: "Long Beach, California, USA",
    key_programs: ["Terran R", "Stargate 3D printer", "Aeon engines"],
    founded_year: 2015,
    employee_count_estimate: 800,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Firefly Aerospace",
    slug: "firefly-aerospace",
    type: "company",
    sectors: ["launch", "lunar", "space systems"],
    description:
      "Launch and space services company operating the Alpha small launch vehicle and developing the MLV medium-lift rocket. Selected by NASA for the Blue Ghost lunar lander under CLPS program.",
    website: "https://fireflyspace.com",
    ticker_symbol: null,
    headquarters: "Cedar Park, Texas, USA",
    key_programs: ["Alpha", "MLV", "Blue Ghost", "Elytra OTV"],
    founded_year: 2014,
    employee_count_estimate: 700,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "ABL Space Systems",
    slug: "abl-space-systems",
    type: "company",
    sectors: ["launch", "responsive space"],
    description:
      "Small launch vehicle developer building the RS1 rocket designed for rapid, containerized launch operations. Focuses on responsive launch capability from austere locations for defense and commercial customers.",
    website: "https://ablspacesystems.com",
    ticker_symbol: null,
    headquarters: "El Segundo, California, USA",
    key_programs: ["RS1", "GS0 ground system", "E2 engine"],
    founded_year: 2017,
    employee_count_estimate: 300,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Astra",
    slug: "astra",
    type: "company",
    sectors: ["launch", "spacecraft propulsion"],
    description:
      "Space technology company that pivoted from small launch vehicles to spacecraft electric propulsion systems. Developing the Astra Spacecraft Engine for satellite maneuvering and orbit transfer.",
    website: "https://www.astra.com",
    ticker_symbol: "ASTR",
    headquarters: "Alameda, California, USA",
    key_programs: ["Astra Spacecraft Engine", "Launch System 2.0"],
    founded_year: 2016,
    employee_count_estimate: 200,
    annual_revenue_estimate: "$5M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Virgin Orbit",
    slug: "virgin-orbit",
    type: "company",
    sectors: ["launch"],
    description:
      "Air-launch-to-orbit company that used a modified Boeing 747 named Cosmic Girl to deploy the LauncherOne rocket. Ceased operations and filed for bankruptcy in 2023 after a failed UK launch attempt.",
    website: "https://virginorbit.com",
    ticker_symbol: null,
    headquarters: "Long Beach, California, USA",
    key_programs: ["LauncherOne", "Cosmic Girl"],
    founded_year: 2017,
    employee_count_estimate: 0,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Arianespace",
    slug: "arianespace",
    type: "company",
    sectors: ["launch", "international"],
    description:
      "European launch services provider and subsidiary of ArianeGroup, operating from the Guiana Space Centre. Transitioning from Ariane 5 to the next-generation Ariane 6 launch vehicle alongside the Vega-C small launcher.",
    website: "https://www.arianespace.com",
    ticker_symbol: null,
    headquarters: "Courcouronnes, France",
    key_programs: ["Ariane 6", "Vega-C", "Ariane 5 legacy", "Starsem Soyuz"],
    founded_year: 1980,
    employee_count_estimate: 400,
    annual_revenue_estimate: "$1.5B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "ISRO",
    slug: "isro",
    type: "agency",
    sectors: ["launch", "government", "civil space"],
    description:
      "Indian Space Research Organisation is India's national space agency responsible for space exploration, satellite launches, and interplanetary missions. Achieved historic success with Chandrayaan-3 lunar landing and operates one of the most cost-effective launch programs globally.",
    website: "https://www.isro.gov.in",
    ticker_symbol: null,
    headquarters: "Bengaluru, India",
    key_programs: ["PSLV", "GSLV Mk III", "Chandrayaan", "Gaganyaan", "Aditya-L1"],
    founded_year: 1969,
    employee_count_estimate: 17000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Roscosmos",
    slug: "roscosmos",
    type: "agency",
    sectors: ["launch", "government", "civil space"],
    description:
      "Russian state space corporation responsible for space flights, cosmonautics programs, and aerospace research. Operates the Soyuz crew vehicle and Proton heavy-lift rocket while developing the next-generation Angara launch family.",
    website: "https://www.roscosmos.ru",
    ticker_symbol: null,
    headquarters: "Moscow, Russia",
    key_programs: ["Soyuz", "Proton", "Angara", "ISS segment operations"],
    founded_year: 1992,
    employee_count_estimate: 170000,
    annual_revenue_estimate: "$3.5B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "CGWIC",
    slug: "cgwic",
    type: "company",
    sectors: ["launch", "international", "satellite export"],
    description:
      "China Great Wall Industry Corporation is the sole commercial entity authorized to provide international space launch services and satellite systems using Chinese Long March rockets. Serves as the export arm of China's space industry.",
    website: "https://www.cgwic.com",
    ticker_symbol: null,
    headquarters: "Beijing, China",
    key_programs: [
      "Long March launch services",
      "DFH satellite platform",
      "In-orbit delivery",
    ],
    founded_year: 1980,
    employee_count_estimate: 10000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
];

// ─── SATELLITE OPERATORS (15) ───────────────────────────────────────────────
const satelliteOperators: SeedEntity[] = [
  {
    name: "Telesat",
    slug: "telesat",
    type: "company",
    sectors: ["satellite_ops", "LEO broadband", "GEO"],
    description:
      "Canadian satellite operator developing the Lightspeed LEO broadband constellation alongside its existing GEO fleet. One of the world's oldest and most established satellite communications companies serving enterprise and government customers.",
    website: "https://www.telesat.com",
    ticker_symbol: "TSAT",
    headquarters: "Ottawa, Canada",
    key_programs: ["Lightspeed LEO", "Anik satellites", "Telstar fleet"],
    founded_year: 1969,
    employee_count_estimate: 900,
    annual_revenue_estimate: "$700M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "OneWeb (Eutelsat OneWeb)",
    slug: "oneweb",
    type: "company",
    sectors: ["satellite_ops", "LEO broadband"],
    description:
      "LEO broadband constellation operator now part of Eutelsat Group following a 2023 merger. Operates a 648-satellite constellation providing connectivity services to enterprise, government, and maritime customers worldwide.",
    website: "https://oneweb.net",
    ticker_symbol: null,
    headquarters: "London, United Kingdom",
    key_programs: ["OneWeb Gen 1 constellation", "OneWeb Gen 2", "Maritime connectivity"],
    founded_year: 2012,
    employee_count_estimate: 500,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Viasat",
    slug: "viasat",
    type: "company",
    sectors: ["satellite_ops", "satellite broadband", "defense communications"],
    description:
      "Global communications company providing broadband and secure networking via satellite. Completed acquisition of Inmarsat in 2023, creating a multi-orbit operator with GEO, MEO, and LEO assets serving commercial aviation, maritime, and defense.",
    website: "https://www.viasat.com",
    ticker_symbol: "VSAT",
    headquarters: "Carlsbad, California, USA",
    key_programs: ["ViaSat-3", "Inmarsat integration", "Link 16", "BATS-D"],
    founded_year: 1986,
    employee_count_estimate: 24000,
    annual_revenue_estimate: "$3.6B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Hughes (EchoStar)",
    slug: "hughes-echostar",
    type: "company",
    sectors: ["satellite_ops", "satellite broadband"],
    description:
      "Leading provider of satellite internet services through HughesNet, operating under parent company EchoStar. Serves over 1.3 million subscribers with broadband connectivity and provides managed network services to enterprise customers.",
    website: "https://www.hughes.com",
    ticker_symbol: "SATS",
    headquarters: "Germantown, Maryland, USA",
    key_programs: ["JUPITER system", "HughesNet", "EchoStar XXIV", "Hughes 63 West"],
    founded_year: 1971,
    employee_count_estimate: 4500,
    annual_revenue_estimate: "$1.6B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Iridium",
    slug: "iridium",
    type: "company",
    sectors: ["satellite_ops", "mobile satellite services"],
    description:
      "Operates the only truly global satellite communications network with 66 crosslinked LEO satellites providing voice, data, and broadband services. The Iridium NEXT constellation enables critical communications for maritime, aviation, IoT, and government users.",
    website: "https://www.iridium.com",
    ticker_symbol: "IRDM",
    headquarters: "McLean, Virginia, USA",
    key_programs: ["Iridium NEXT", "Iridium Certus", "GMDSS", "Iridium PTT"],
    founded_year: 2000,
    employee_count_estimate: 700,
    annual_revenue_estimate: "$780M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Globalstar",
    slug: "globalstar",
    type: "company",
    sectors: ["satellite_ops", "mobile satellite services", "IoT"],
    description:
      "LEO satellite communications company providing voice, data, and IoT connectivity services. Partnered with Apple for iPhone 14+ Emergency SOS via satellite feature, driving significant new revenue and planned constellation expansion.",
    website: "https://www.globalstar.com",
    ticker_symbol: "GSAT",
    headquarters: "Covington, Louisiana, USA",
    key_programs: ["Globalstar constellation", "SPOT tracking", "Band n53", "Apple SOS"],
    founded_year: 1991,
    employee_count_estimate: 450,
    annual_revenue_estimate: "$250M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Orbcomm",
    slug: "orbcomm",
    type: "company",
    sectors: ["satellite_ops", "IoT", "fleet management"],
    description:
      "Industrial IoT and satellite-based connectivity provider specializing in machine-to-machine communication. Operates a LEO satellite constellation and provides fleet management, asset tracking, and cold chain monitoring for transportation and logistics.",
    website: "https://www.orbcomm.com",
    ticker_symbol: null,
    headquarters: "Rochelle Park, New Jersey, USA",
    key_programs: ["OG2 constellation", "FleetManager", "IoT platform", "Cold chain monitoring"],
    founded_year: 1993,
    employee_count_estimate: 600,
    annual_revenue_estimate: "$280M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Planet Labs",
    slug: "planet-labs",
    type: "company",
    sectors: ["satellite_ops", "Earth observation", "remote sensing"],
    description:
      "Operates the largest fleet of Earth-imaging satellites, capturing the entire planet daily with its SuperDove constellation. Provides geospatial data and analytics for agriculture, forestry, government intelligence, and climate monitoring applications.",
    website: "https://www.planet.com",
    ticker_symbol: "PL",
    headquarters: "San Francisco, California, USA",
    key_programs: ["PlanetScope", "SkySat", "Pelican", "Tanager hyperspectral"],
    founded_year: 2010,
    employee_count_estimate: 900,
    annual_revenue_estimate: "$220M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "BlackSky",
    slug: "blacksky-technology",
    type: "company",
    sectors: ["satellite_ops", "Earth observation", "geospatial intelligence"],
    description:
      "Real-time geospatial intelligence company combining high-revisit satellite imagery with AI-driven analytics. Operates Gen-3 small satellites providing dawn-to-dusk imaging with rapid tasking for defense, intelligence, and commercial customers.",
    website: "https://www.blacksky.com",
    ticker_symbol: "BKSY",
    headquarters: "Herndon, Virginia, USA",
    key_programs: ["Gen-3 satellites", "Spectra AI platform", "On-demand imaging", "LightSpeed analytics"],
    founded_year: 2014,
    employee_count_estimate: 400,
    annual_revenue_estimate: "$100M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Maxar",
    slug: "maxar-technologies",
    type: "company",
    sectors: ["satellite_ops", "Earth observation", "satellites", "robotics"],
    description:
      "Leading provider of high-resolution Earth observation imagery and satellite manufacturing. Acquired by Advent International in 2023, operates WorldView Legion next-gen imaging constellation and builds commercial communication satellites.",
    website: "https://www.maxar.com",
    ticker_symbol: null,
    headquarters: "Westminster, Colorado, USA",
    key_programs: ["WorldView Legion", "SSL satellite buses", "Robotics (MDA legacy)", "Vricon 3D"],
    founded_year: 2017,
    employee_count_estimate: 5600,
    annual_revenue_estimate: "$1.8B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Spire Global",
    slug: "spire-global",
    type: "company",
    sectors: ["satellite_ops", "data analytics", "maritime", "weather"],
    description:
      "Space-to-cloud analytics company operating a constellation of multipurpose nanosatellites collecting maritime AIS, aviation ADS-B, weather, and Earth observation data. Provides space-as-a-service hosting payloads for third-party customers.",
    website: "https://spire.com",
    ticker_symbol: "SPIR",
    headquarters: "Vienna, Virginia, USA",
    key_programs: ["LEMUR nanosats", "Maritime AIS", "Weather GNSS-RO", "Space Services"],
    founded_year: 2012,
    employee_count_estimate: 500,
    annual_revenue_estimate: "$100M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "HawkEye 360",
    slug: "hawkeye-360",
    type: "company",
    sectors: ["satellite_ops", "RF geolocation", "signals intelligence"],
    description:
      "Radio frequency (RF) data analytics company operating satellite clusters that detect, characterize, and geolocate RF signals from space. Provides maritime domain awareness, spectrum monitoring, and defense intelligence services.",
    website: "https://www.he360.com",
    ticker_symbol: null,
    headquarters: "Herndon, Virginia, USA",
    key_programs: ["Clusters 1-8", "RF signal geolocation", "Maritime awareness", "Spectrum mapping"],
    founded_year: 2015,
    employee_count_estimate: 350,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Capella Space",
    slug: "capella-space",
    type: "company",
    sectors: ["satellite_ops", "SAR", "Earth observation"],
    description:
      "Synthetic aperture radar (SAR) satellite company providing all-weather, day-and-night Earth imaging. Operates the Acadia constellation delivering sub-meter resolution SAR imagery for defense, intelligence, and commercial applications.",
    website: "https://www.capellaspace.com",
    ticker_symbol: null,
    headquarters: "San Francisco, California, USA",
    key_programs: ["Acadia SAR satellites", "Console tasking platform", "Automated change detection"],
    founded_year: 2016,
    employee_count_estimate: 300,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "ICEYE",
    slug: "iceye",
    type: "company",
    sectors: ["satellite_ops", "SAR", "natural catastrophe"],
    description:
      "Finnish SAR microsatellite operator providing persistent radar imaging for natural catastrophe monitoring, insurance, and defense. Pioneered commercially accessible SAR satellite technology with the world's largest SAR constellation.",
    website: "https://www.iceye.com",
    ticker_symbol: null,
    headquarters: "Espoo, Finland",
    key_programs: ["SAR microsatellites", "Flood monitoring", "NatCat insights", "Defense persistent monitoring"],
    founded_year: 2014,
    employee_count_estimate: 600,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Muon Space",
    slug: "muon-space",
    type: "company",
    sectors: ["satellite_ops", "climate", "weather"],
    description:
      "Vertically integrated satellite company building and operating multimodal weather and climate monitoring satellites. Designs, manufactures, and operates purpose-built Earth observation satellites focused on climate data gaps.",
    website: "https://www.muonspace.com",
    ticker_symbol: null,
    headquarters: "Mountain View, California, USA",
    key_programs: ["MuSat-1", "Climate monitoring constellation", "Microwave radiometry"],
    founded_year: 2021,
    employee_count_estimate: 100,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
];

// ─── DEFENSE PRIMES (10) ────────────────────────────────────────────────────
const defensePrimes: SeedEntity[] = [
  {
    name: "Lockheed Martin",
    slug: "lockheed-martin",
    type: "company",
    sectors: ["defense", "satellites", "missiles", "space systems"],
    description:
      "World's largest defense contractor and a leading space systems prime. Builds the Orion crew capsule for Artemis, GPS III navigation satellites, and Next Gen OPIR missile warning constellation alongside flagship programs like F-35 and THAAD.",
    website: "https://www.lockheedmartin.com",
    ticker_symbol: "LMT",
    headquarters: "Bethesda, Maryland, USA",
    key_programs: ["F-35", "Orion", "GPS III", "Next Gen OPIR", "THAAD"],
    founded_year: 1995,
    employee_count_estimate: 122000,
    annual_revenue_estimate: "$67.6B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Northrop Grumman",
    slug: "northrop-grumman",
    type: "company",
    sectors: ["defense", "launch", "satellites", "space systems"],
    description:
      "Major aerospace and defense technology company building the B-21 Raider stealth bomber, James Webb Space Telescope, and solid rocket boosters for multiple launch vehicles. Operates the Cygnus cargo spacecraft and Mission Extension Vehicle for satellite servicing.",
    website: "https://www.northropgrumman.com",
    ticker_symbol: "NOC",
    headquarters: "Falls Church, Virginia, USA",
    key_programs: ["B-21 Raider", "JWST", "Cygnus", "GBSD Sentinel", "MEV"],
    founded_year: 1994,
    employee_count_estimate: 95000,
    annual_revenue_estimate: "$39.3B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "RTX",
    slug: "rtx-raytheon",
    type: "company",
    sectors: ["defense", "missiles", "sensors", "propulsion"],
    description:
      "Aerospace and defense conglomerate formed from the merger of Raytheon and United Technologies. Comprises Collins Aerospace, Pratt & Whitney engines, and Raytheon missiles and defense systems serving both commercial aerospace and military customers worldwide.",
    website: "https://www.rtx.com",
    ticker_symbol: "RTX",
    headquarters: "Arlington, Virginia, USA",
    key_programs: ["Patriot", "SM-3", "Pratt & Whitney engines", "Collins Aerospace", "StormBreaker"],
    founded_year: 2020,
    employee_count_estimate: 185000,
    annual_revenue_estimate: "$68.9B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "General Dynamics",
    slug: "general-dynamics",
    type: "company",
    sectors: ["defense", "IT services", "marine systems"],
    description:
      "Diversified defense and aerospace company operating across combat systems, marine systems, IT, and business aviation. Builds Columbia-class ballistic missile submarines, Abrams tanks, and provides enterprise IT services through GDIT.",
    website: "https://www.gd.com",
    ticker_symbol: "GD",
    headquarters: "Reston, Virginia, USA",
    key_programs: ["Columbia-class submarine", "Gulfstream", "GDIT", "Abrams", "Stryker"],
    founded_year: 1952,
    employee_count_estimate: 112000,
    annual_revenue_estimate: "$42.3B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "BAE Systems",
    slug: "bae-systems",
    type: "company",
    sectors: ["defense", "electronic warfare", "satellites"],
    description:
      "Global defense, security, and aerospace company headquartered in the UK. Growing presence in space electronic warfare and satellite systems alongside core programs including Typhoon fighter, Tempest next-gen combat air, and Astute-class submarine.",
    website: "https://www.baesystems.com",
    ticker_symbol: "BA.",
    headquarters: "London, United Kingdom",
    key_programs: ["Typhoon", "Tempest", "Astute submarine", "EW suites", "Striker II"],
    founded_year: 1999,
    employee_count_estimate: 100000,
    annual_revenue_estimate: "$27.6B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "L3Harris",
    slug: "l3harris-technologies",
    type: "company",
    sectors: ["defense", "satellites", "ISR", "sensors"],
    description:
      "Defense technology company formed from the merger of L3 Technologies and Harris Corporation. Leads in responsive space satellites, tactical communications, ISR sensors, and electronic warfare systems serving all branches of the U.S. military.",
    website: "https://www.l3harris.com",
    ticker_symbol: "LHX",
    headquarters: "Melbourne, Florida, USA",
    key_programs: ["Responsive space", "WESCAM sensors", "Tactical radios", "IVAS", "T7 robot"],
    founded_year: 2019,
    employee_count_estimate: 50000,
    annual_revenue_estimate: "$21.1B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Leidos",
    slug: "leidos",
    type: "company",
    sectors: ["defense", "IT services", "space systems"],
    description:
      "Science and technology company providing IT, engineering, and defense solutions to government and commercial customers. Operates the Dynetics space division building spacecraft and missile defense interceptors for the Department of Defense.",
    website: "https://www.leidos.com",
    ticker_symbol: "LDOS",
    headquarters: "Reston, Virginia, USA",
    key_programs: ["NGEN IT", "DMSS", "Enduring Shield", "Dynetics", "SMSS"],
    founded_year: 2013,
    employee_count_estimate: 47000,
    annual_revenue_estimate: "$15.4B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "SAIC",
    slug: "saic",
    type: "company",
    sectors: ["defense", "IT services", "digital transformation"],
    description:
      "Technology integrator providing IT modernization, engineering services, and digital solutions to U.S. defense, intelligence, and civilian agencies. Supports NASA mission operations and Department of Defense cloud and AI initiatives.",
    website: "https://www.saic.com",
    ticker_symbol: "SAIC",
    headquarters: "Reston, Virginia, USA",
    key_programs: ["NASA ACES", "IT modernization", "Cloud migration", "Digital engineering"],
    founded_year: 2013,
    employee_count_estimate: 26000,
    annual_revenue_estimate: "$7.4B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Parsons",
    slug: "parsons",
    type: "company",
    sectors: ["defense", "infrastructure", "cyber"],
    description:
      "Technology-focused defense, intelligence, and infrastructure company. Provides missile defense engineering, cyber operations, and space ground systems integration alongside critical infrastructure projects for government customers.",
    website: "https://www.parsons.com",
    ticker_symbol: "PSN",
    headquarters: "Centreville, Virginia, USA",
    key_programs: ["Missile defense engineering", "Cyber operations", "Critical infrastructure", "Space ground systems"],
    founded_year: 1944,
    employee_count_estimate: 17500,
    annual_revenue_estimate: "$5.4B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Peraton",
    slug: "peraton",
    type: "company",
    sectors: ["defense", "intelligence", "space"],
    description:
      "National security company providing signals intelligence, satellite ground systems, and mission-critical IT services to the intelligence community and DoD. One of the largest private defense IT companies backed by Veritas Capital.",
    website: "https://www.peraton.com",
    ticker_symbol: null,
    headquarters: "Herndon, Virginia, USA",
    key_programs: ["NROL missions support", "Signals intelligence", "Satellite ground systems", "Cyber operations"],
    founded_year: 2017,
    employee_count_estimate: 18000,
    annual_revenue_estimate: "$7B",
    last_activity: null,
    source_counts: {},
  },
];

// ─── GOVERNMENT AGENCIES (10) ───────────────────────────────────────────────
const governmentAgencies: SeedEntity[] = [
  {
    name: "NASA",
    slug: "nasa",
    type: "agency",
    sectors: ["government", "civil space", "exploration", "science"],
    description:
      "U.S. civil space agency leading the Artemis program to return humans to the Moon, operating the International Space Station, and conducting planetary science and Earth observation missions. Manages commercial crew and cargo partnerships with private industry.",
    website: "https://www.nasa.gov",
    ticker_symbol: null,
    headquarters: "Washington, D.C., USA",
    key_programs: ["Artemis", "ISS", "Commercial Crew", "Mars Sample Return", "SLS"],
    founded_year: 1958,
    employee_count_estimate: 18000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "USSF",
    slug: "space-force-ussf",
    type: "agency",
    sectors: ["government", "military space", "space domain awareness"],
    description:
      "United States Space Force is the space service branch of the U.S. Armed Forces responsible for organizing, training, and equipping space forces. Operates GPS, missile warning, and space surveillance systems to ensure freedom of action in space.",
    website: "https://www.spaceforce.mil",
    ticker_symbol: null,
    headquarters: "Pentagon, Arlington, Virginia, USA",
    key_programs: ["GPS", "SBIRS", "Space Fence", "National Security Space Launch", "Resilient SATCOM"],
    founded_year: 2019,
    employee_count_estimate: 16000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "NRO",
    slug: "nro",
    type: "agency",
    sectors: ["government", "ISR", "national security space", "reconnaissance"],
    description:
      "National Reconnaissance Office designs, builds, launches, and operates the nation's reconnaissance satellites. Provides intelligence derived from satellite reconnaissance to the CIA, DoD, and other intelligence community members.",
    website: "https://www.nro.gov",
    ticker_symbol: null,
    headquarters: "Chantilly, Virginia, USA",
    key_programs: ["Electro-optical reconnaissance", "Signals intelligence satellites", "NROL missions", "Proliferated architecture"],
    founded_year: 1961,
    employee_count_estimate: 3000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "DARPA",
    slug: "darpa",
    type: "agency",
    sectors: ["government", "defense R&D", "space technology"],
    description:
      "Defense Advanced Research Projects Agency creates breakthrough technologies and capabilities for national security. Funds high-risk, high-reward space programs including Blackjack mesh satellite network and DRACO nuclear thermal propulsion.",
    website: "https://www.darpa.mil",
    ticker_symbol: null,
    headquarters: "Arlington, Virginia, USA",
    key_programs: ["Blackjack", "DRACO nuclear propulsion", "Gambit", "Hallmark", "RSGS"],
    founded_year: 1958,
    employee_count_estimate: 220,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "CISA",
    slug: "cisa",
    type: "agency",
    sectors: ["government", "cybersecurity", "critical infrastructure"],
    description:
      "Cybersecurity and Infrastructure Security Agency is the U.S. federal agency responsible for protecting critical infrastructure from cyber and physical threats. Increasingly relevant to space sector as satellite systems become critical infrastructure targets.",
    website: "https://www.cisa.gov",
    ticker_symbol: null,
    headquarters: "Arlington, Virginia, USA",
    key_programs: ["Shields Up", "JCDC", "Known Exploited Vulnerabilities catalog", "Critical Infrastructure Protection"],
    founded_year: 2018,
    employee_count_estimate: 3200,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "NOAA",
    slug: "noaa",
    type: "agency",
    sectors: ["government", "weather", "Earth observation"],
    description:
      "National Oceanic and Atmospheric Administration operates the nation's weather and environmental satellite systems. GOES geostationary and JPSS polar-orbiting satellites provide critical weather forecasting and climate monitoring data.",
    website: "https://www.noaa.gov",
    ticker_symbol: null,
    headquarters: "Silver Spring, Maryland, USA",
    key_programs: ["GOES satellites", "JPSS", "NESDIS", "Weather forecasting", "Space weather"],
    founded_year: 1970,
    employee_count_estimate: 12000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "FAA AST",
    slug: "faa-ast",
    type: "agency",
    sectors: ["government", "regulation", "launch licensing"],
    description:
      "FAA Office of Commercial Space Transportation licenses and regulates commercial launch and reentry operations in the United States. Responsible for protecting public safety during commercial space activities under Part 450 streamlined licensing framework.",
    website: "https://www.faa.gov/space",
    ticker_symbol: null,
    headquarters: "Washington, D.C., USA",
    key_programs: ["Launch licensing", "Reentry authorization", "Part 450 framework", "Spaceport regulation"],
    founded_year: 1984,
    employee_count_estimate: 120,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "FCC",
    slug: "fcc",
    type: "agency",
    sectors: ["government", "spectrum regulation", "satellite licensing"],
    description:
      "Federal Communications Commission regulates satellite communications licensing, spectrum allocation, and orbital debris mitigation for commercial satellite operators. Key gatekeeper for NGSO constellation approvals and spectrum coordination.",
    website: "https://www.fcc.gov",
    ticker_symbol: null,
    headquarters: "Washington, D.C., USA",
    key_programs: ["Spectrum allocation", "NGSO licensing", "Orbital debris rules", "12 GHz proceedings"],
    founded_year: 1934,
    employee_count_estimate: 1500,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "NTIA",
    slug: "ntia",
    type: "agency",
    sectors: ["government", "spectrum management", "telecommunications"],
    description:
      "National Telecommunications and Information Administration advises the President on telecommunications and information policy. Manages federal spectrum use and administers broadband infrastructure grants including the BEAD program.",
    website: "https://www.ntia.gov",
    ticker_symbol: null,
    headquarters: "Washington, D.C., USA",
    key_programs: ["Federal spectrum management", "BEAD broadband", "Spectrum sharing", "Institute for Telecommunication Sciences"],
    founded_year: 1978,
    employee_count_estimate: 300,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "SDA",
    slug: "sda",
    type: "agency",
    sectors: ["government", "military space", "missile tracking"],
    description:
      "Space Development Agency builds and fields the Proliferated Warfighter Space Architecture (PWSA) — a mesh network of hundreds of satellites in LEO for missile tracking and data transport. Transitioned into the U.S. Space Force in 2023.",
    website: "https://www.sda.mil",
    ticker_symbol: null,
    headquarters: "Arlington, Virginia, USA",
    key_programs: ["PWSA", "Transport Layer", "Tracking Layer", "Tranche 0/1/2"],
    founded_year: 2019,
    employee_count_estimate: 250,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
];

// ─── EMERGING / NEWSPACE (15) ───────────────────────────────────────────────
const emergingNewspace: SeedEntity[] = [
  {
    name: "Impulse Space",
    slug: "impulse-space",
    type: "company",
    sectors: ["newspace", "orbital transfer", "in-space transportation"],
    description:
      "In-space transportation company founded by former SpaceX Merlin engine lead Tom Mueller. Developing the Mira orbital transfer vehicle and Helios deep-space tug to provide last-mile delivery services for satellite constellations and beyond.",
    website: "https://www.impulsespace.com",
    ticker_symbol: null,
    headquarters: "Redondo Beach, California, USA",
    key_programs: ["Mira OTV", "Helios tug", "Propulsion systems"],
    founded_year: 2021,
    employee_count_estimate: 200,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Astroscale",
    slug: "astroscale",
    type: "company",
    sectors: ["newspace", "debris removal", "on-orbit servicing"],
    description:
      "On-orbit servicing company developing technologies for space debris removal and satellite life extension. Successfully demonstrated close-proximity rendezvous with debris via the ADRAS-J mission and pursuing commercial debris removal services.",
    website: "https://astroscale.com",
    ticker_symbol: "186A",
    headquarters: "Tokyo, Japan",
    key_programs: ["ADRAS-J", "ELSA-d", "COSMIC", "Active debris removal"],
    founded_year: 2013,
    employee_count_estimate: 500,
    annual_revenue_estimate: "$30M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "ClearSpace",
    slug: "clearspace",
    type: "company",
    sectors: ["newspace", "debris removal", "on-orbit servicing"],
    description:
      "Swiss space debris removal company selected by ESA to lead the ClearSpace-1 mission — the first-ever active debris removal mission. Developing capture and deorbiting technologies for a sustainable space environment.",
    website: "https://clearspace.today",
    ticker_symbol: null,
    headquarters: "Renens, Switzerland",
    key_programs: ["ClearSpace-1", "ESA Active Debris Removal", "Capture mechanisms"],
    founded_year: 2018,
    employee_count_estimate: 100,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Privateer",
    slug: "privateer",
    type: "company",
    sectors: ["newspace", "space sustainability", "space domain awareness"],
    description:
      "Space sustainability data company co-founded by Steve Wozniak building the Wayfinder platform for mapping and tracking space objects. Focuses on making space environmentally sustainable through better data transparency and shared awareness.",
    website: "https://www.privateer.com",
    ticker_symbol: null,
    headquarters: "Maui, Hawaii, USA",
    key_programs: ["Wayfinder SSA platform", "Pono sustainability rating", "Space data commons"],
    founded_year: 2021,
    employee_count_estimate: 50,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "LeoLabs",
    slug: "leolabs",
    type: "company",
    sectors: ["newspace", "space domain awareness", "SSA"],
    description:
      "Space situational awareness company operating a global network of phased-array radars that track objects in low Earth orbit. Provides conjunction assessment, collision avoidance, and mapping services to satellite operators and government agencies.",
    website: "https://leolabs.space",
    ticker_symbol: null,
    headquarters: "Menlo Park, California, USA",
    key_programs: ["Phased-array radar network", "LEO mapping", "Conjunction assessment", "Collision avoidance"],
    founded_year: 2016,
    employee_count_estimate: 100,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "ExoAnalytic Solutions",
    slug: "exoanalytic-solutions",
    type: "company",
    sectors: ["newspace", "space domain awareness", "optical tracking"],
    description:
      "Space domain awareness company operating the world's largest commercial optical telescope network for tracking objects in all orbital regimes. Provides space object characterization, maneuver detection, and catalog services to government and commercial customers.",
    website: "https://exoanalytic.com",
    ticker_symbol: null,
    headquarters: "Moorpark, California, USA",
    key_programs: ["Global telescope network", "ExoAnalytic SDA platform", "Object characterization", "Maneuver detection"],
    founded_year: 2009,
    employee_count_estimate: 150,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Slingshot Aerospace",
    slug: "slingshot-aerospace",
    type: "company",
    sectors: ["newspace", "space domain awareness", "digital twin"],
    description:
      "Space data and simulation company building digital twin technology for the space domain. Provides real-time space situational awareness, conjunction assessment, and training tools for U.S. Space Force and commercial satellite operators.",
    website: "https://slingshotaerospace.com",
    ticker_symbol: null,
    headquarters: "Austin, Texas, USA",
    key_programs: ["Slingshot Beacon", "Digital twin space environment", "Seradata integration", "SSA analytics"],
    founded_year: 2017,
    employee_count_estimate: 200,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "True Anomaly",
    slug: "true-anomaly",
    type: "company",
    sectors: ["newspace", "space security", "autonomous spacecraft"],
    description:
      "Space security company developing autonomous spacecraft and software for space domain awareness and defense. Building the Jackal autonomous orbital vehicle and Mosaic software platform for real-time space operations intelligence.",
    website: "https://www.trueanomaly.space",
    ticker_symbol: null,
    headquarters: "Denver, Colorado, USA",
    key_programs: ["Jackal autonomous spacecraft", "Mosaic SDA software", "Space defense operations"],
    founded_year: 2022,
    employee_count_estimate: 200,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Anduril",
    slug: "anduril",
    type: "company",
    sectors: ["newspace", "defense tech", "autonomous systems"],
    description:
      "Defense technology company building autonomous systems and AI-powered command and control software. Lattice OS platform integrates sensors and effectors across domains while hardware products like Fury autonomous jet and Pulsar EW system serve frontline forces.",
    website: "https://www.anduril.com",
    ticker_symbol: null,
    headquarters: "Costa Mesa, California, USA",
    key_programs: ["Lattice OS", "Fury", "Ghost drone", "Pulsar EW", "Dive-LD"],
    founded_year: 2017,
    employee_count_estimate: 4000,
    annual_revenue_estimate: "$1.5B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Shield AI",
    slug: "shield-ai",
    type: "company",
    sectors: ["newspace", "defense tech", "autonomous systems"],
    description:
      "Defense AI company building the Hivemind autonomy stack that enables unmanned systems to operate without GPS, communications, or remote pilots. Platforms include V-BAT vertical takeoff drone and Nova quadcopter for building clearance.",
    website: "https://shield.ai",
    ticker_symbol: null,
    headquarters: "San Diego, California, USA",
    key_programs: ["Hivemind autonomy", "V-BAT", "Nova drone", "MQ-35A"],
    founded_year: 2015,
    employee_count_estimate: 1000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Hadrian",
    slug: "hadrian",
    type: "company",
    sectors: ["newspace", "manufacturing", "supply chain"],
    description:
      "Autonomous precision manufacturing company building factories that produce high-precision parts for aerospace and defense. Uses AI-driven CNC machining and the Flow software platform to reduce lead times from months to days.",
    website: "https://www.hadrian.co",
    ticker_symbol: null,
    headquarters: "Torrance, California, USA",
    key_programs: ["Autonomous CNC factories", "Flow software", "Precision aerospace parts"],
    founded_year: 2020,
    employee_count_estimate: 500,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Apex Space",
    slug: "apex-space",
    type: "company",
    sectors: ["newspace", "satellite buses", "spacecraft manufacturing"],
    description:
      "Satellite bus manufacturer building standardized, rapidly producible spacecraft platforms. The Aries satellite bus enables customers to integrate their payloads onto a proven platform with dramatically shorter lead times than traditional satellite manufacturing.",
    website: "https://www.apex.aero",
    ticker_symbol: null,
    headquarters: "Los Angeles, California, USA",
    key_programs: ["Aries satellite bus", "Modular spacecraft platform", "Rapid integration"],
    founded_year: 2022,
    employee_count_estimate: 100,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Albedo",
    slug: "albedo",
    type: "company",
    sectors: ["newspace", "Earth observation", "VLEO"],
    description:
      "Very low Earth orbit (VLEO) imaging company building satellites to capture 10-centimeter resolution visible and 2-meter thermal infrared imagery. Operating below traditional satellite altitudes to deliver unprecedented commercial image resolution.",
    website: "https://albedo.com",
    ticker_symbol: null,
    headquarters: "Broomfield, Colorado, USA",
    key_programs: ["10cm VLEO imaging", "Thermal infrared", "VLEO satellite constellation"],
    founded_year: 2020,
    employee_count_estimate: 150,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Umbra",
    slug: "umbra",
    type: "company",
    sectors: ["newspace", "SAR", "Earth observation"],
    description:
      "SAR satellite operator providing high-resolution, all-weather radar imagery on demand. Operates one of the highest-resolution commercial SAR constellations with an open data access model and rapid tasking capabilities.",
    website: "https://umbra.space",
    ticker_symbol: null,
    headquarters: "Santa Barbara, California, USA",
    key_programs: ["SAR satellites", "Open data platform", "Canopy analytics", "Spotlight mode"],
    founded_year: 2015,
    employee_count_estimate: 200,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Pixxel",
    slug: "pixxel",
    type: "company",
    sectors: ["newspace", "hyperspectral", "Earth observation"],
    description:
      "Indian hyperspectral Earth observation company building the world's highest-resolution commercial hyperspectral satellite constellation. Captures data across hundreds of spectral bands enabling precision agriculture, mining, and environmental monitoring analytics.",
    website: "https://www.pixxel.space",
    ticker_symbol: null,
    headquarters: "Bengaluru, India",
    key_programs: ["Firefly hyperspectral satellites", "Aurora analytics platform", "Honeybee constellation"],
    founded_year: 2019,
    employee_count_estimate: 200,
    annual_revenue_estimate: "Pre-revenue",
    last_activity: null,
    source_counts: {},
  },
];

// ─── INTERNATIONAL (10) ─────────────────────────────────────────────────────
const internationalEntities: SeedEntity[] = [
  {
    name: "Airbus Defence and Space",
    slug: "airbus-defence-and-space",
    type: "company",
    sectors: ["international", "satellites", "defense", "launch"],
    description:
      "European aerospace division of Airbus SE encompassing military aircraft, space systems, and intelligence. Builds the Ariane 6 upper stage, Pléiades Neo imaging constellation, OneWeb satellites, and the Eurostar Neo communications platform.",
    website: "https://www.airbus.com/en/space",
    ticker_symbol: "AIR",
    headquarters: "Ottobrunn, Germany",
    key_programs: ["Ariane 6", "Pléiades Neo", "Skynet", "Eurostar Neo", "OneSat"],
    founded_year: 2014,
    employee_count_estimate: 35000,
    annual_revenue_estimate: "$13.9B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Thales Alenia Space",
    slug: "thales-alenia-space",
    type: "company",
    sectors: ["international", "satellites", "telecommunications"],
    description:
      "Joint venture between Thales and Leonardo providing space systems for telecommunications, navigation, Earth observation, and exploration. Built Iridium NEXT satellites and develops habitation modules for lunar Gateway and Axiom space station.",
    website: "https://www.thalesaleniaspace.com",
    ticker_symbol: null,
    headquarters: "Cannes, France",
    key_programs: ["Iridium NEXT", "SpaceInspire", "COSMO-SkyMed", "Axiom modules", "Galileo"],
    founded_year: 2007,
    employee_count_estimate: 8800,
    annual_revenue_estimate: "$2.8B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "OHB SE",
    slug: "ohb-se",
    type: "company",
    sectors: ["international", "satellites", "space systems"],
    description:
      "German space and technology company building satellites for navigation, reconnaissance, and weather monitoring. Key European contractor for Galileo navigation satellites, SARah radar reconnaissance, and Meteosat Third Generation weather systems.",
    website: "https://www.ohb.de",
    ticker_symbol: "OHB",
    headquarters: "Bremen, Germany",
    key_programs: ["Galileo satellites", "SARah radar", "MTG weather", "Arctic Weather Satellite"],
    founded_year: 1981,
    employee_count_estimate: 3500,
    annual_revenue_estimate: "$1.1B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "MDA Space",
    slug: "mda-space",
    type: "company",
    sectors: ["international", "robotics", "satellites", "Earth observation"],
    description:
      "Canadian space technology company known for building the Canadarm robotic systems for the Space Shuttle and ISS. Developing Canadarm3 for the Lunar Gateway and operating RADARSAT SAR Earth observation constellation for the Canadian government.",
    website: "https://mda.space",
    ticker_symbol: "MDA",
    headquarters: "Brampton, Ontario, Canada",
    key_programs: ["Canadarm3", "RADARSAT", "MDA AURORA", "Satellite servicing"],
    founded_year: 1969,
    employee_count_estimate: 3200,
    annual_revenue_estimate: "$600M",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "KARI",
    slug: "kari",
    type: "agency",
    sectors: ["international", "government", "launch", "exploration"],
    description:
      "Korea Aerospace Research Institute is South Korea's national aerospace research organization. Successfully launched the Nuri (KSLV-II) indigenous rocket and operates KOMPSAT Earth observation satellites while developing lunar and deep space exploration capabilities.",
    website: "https://www.kari.re.kr",
    ticker_symbol: null,
    headquarters: "Daejeon, South Korea",
    key_programs: ["Nuri (KSLV-II)", "KOMPSAT", "Korea Pathfinder Lunar Orbiter", "Next-gen launch vehicle"],
    founded_year: 1989,
    employee_count_estimate: 1000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "JAXA",
    slug: "jaxa",
    type: "agency",
    sectors: ["international", "government", "exploration", "launch"],
    description:
      "Japan Aerospace Exploration Agency conducts space research, planetary exploration, and operates Japan's launch vehicle fleet. Achieved precision lunar landing with SLIM mission, operates the H3 rocket, and contributed major ISS module Kibo.",
    website: "https://www.jaxa.jp",
    ticker_symbol: null,
    headquarters: "Chofu, Tokyo, Japan",
    key_programs: ["H3 rocket", "Hayabusa2", "SLIM lunar lander", "QZSS", "Kibo"],
    founded_year: 2003,
    employee_count_estimate: 1500,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "CNSA",
    slug: "cnsa",
    type: "agency",
    sectors: ["international", "government", "exploration", "space station"],
    description:
      "China National Space Administration is responsible for China's civil space program. Operates the Tiangong space station, achieved the first far-side lunar landing with Chang'e-4, and deployed the Zhurong Mars rover via the Tianwen-1 mission.",
    website: "https://www.cnsa.gov.cn",
    ticker_symbol: null,
    headquarters: "Beijing, China",
    key_programs: ["Tiangong", "Chang'e lunar", "Tianwen Mars", "Long March family", "Beidou"],
    founded_year: 1993,
    employee_count_estimate: 1000,
    annual_revenue_estimate: null,
    last_activity: null,
    source_counts: {},
  },
  {
    name: "IAI",
    slug: "iai",
    type: "company",
    sectors: ["international", "defense", "satellites", "missiles"],
    description:
      "Israel Aerospace Industries is Israel's largest defense company producing satellites, missile defense systems, and UAVs. Built the Ofeq reconnaissance satellite series and Arrow missile defense system, and attempted the Beresheet private lunar lander.",
    website: "https://www.iai.co.il",
    ticker_symbol: null,
    headquarters: "Lod, Israel",
    key_programs: ["Ofeq satellites", "Arrow missile", "MALD", "Beresheet", "Heron UAV"],
    founded_year: 1953,
    employee_count_estimate: 15000,
    annual_revenue_estimate: "$5B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Rafael Advanced Defense Systems",
    slug: "rafael-advanced-defense-systems",
    type: "company",
    sectors: ["international", "defense", "missiles", "electronic warfare"],
    description:
      "Israeli defense technology company developing advanced weapon systems, military electronics, and space capabilities. Creator of the Iron Dome missile defense system, David's Sling, and Trophy active protection system deployed on armored vehicles worldwide.",
    website: "https://www.rafael.co.il",
    ticker_symbol: null,
    headquarters: "Haifa, Israel",
    key_programs: ["Iron Dome", "David's Sling", "Trophy APS", "Spice bombs", "Lite Shield"],
    founded_year: 1948,
    employee_count_estimate: 8500,
    annual_revenue_estimate: "$3.5B",
    last_activity: null,
    source_counts: {},
  },
  {
    name: "Saab AB",
    slug: "saab-ab",
    type: "company",
    sectors: ["international", "defense", "surveillance", "electronic warfare"],
    description:
      "Swedish aerospace and defense company producing the Gripen multirole fighter, GlobalEye airborne early warning system, and advanced radar and electronic warfare systems. Growing space presence through satellite subsystems and ground segment solutions.",
    website: "https://www.saab.com",
    ticker_symbol: "SAAB-B",
    headquarters: "Linköping, Sweden",
    key_programs: ["Gripen", "GlobalEye", "RBS 15", "Arthur radar", "Carl-Gustaf"],
    founded_year: 1937,
    employee_count_estimate: 22000,
    annual_revenue_estimate: "$6.5B",
    last_activity: null,
    source_counts: {},
  },
];

// ─── MAIN SEED FUNCTION ─────────────────────────────────────────────────────
const allEntities: SeedEntity[] = [
  ...launchProviders,
  ...satelliteOperators,
  ...defensePrimes,
  ...governmentAgencies,
  ...emergingNewspace,
  ...internationalEntities,
];

async function seed() {
  console.log(`Seeding ${allEntities.length} entities...`);

  // Upsert in batches of 20 to avoid payload limits
  const batchSize = 20;
  let totalUpserted = 0;

  for (let i = 0; i < allEntities.length; i += batchSize) {
    const batch = allEntities.slice(i, i + batchSize);
    const { data, error } = await supabase
      .from("entities")
      .upsert(batch, { onConflict: "slug" })
      .select("id");

    if (error) {
      console.error(
        `Error upserting batch ${i / batchSize + 1}:`,
        error.message
      );
      process.exit(1);
    }

    totalUpserted += data.length;
    console.log(
      `  Batch ${i / batchSize + 1}: upserted ${data.length} entities`
    );
  }

  console.log(`\nSuccessfully upserted ${totalUpserted} entities.`);

  // Verify total count
  const { count, error: countError } = await supabase
    .from("entities")
    .select("*", { count: "exact", head: true });

  if (countError) {
    console.error("Error counting entities:", countError.message);
  } else {
    console.log(`Total entities in database: ${count}`);
  }
}

seed();
